### ISSUE TITLE
undefined method `parameters' for #<yardoc class Roby::Task> when opening class that works with 0.9.25 locally

### ISSUE THREAD

**Issue by doudou** [docmeta/rubydoc.info#146]
Hi. First of all, many thanks for maintaining this awesome resource ...

Opening https://www.rubydoc.info/github/rock-core/tools-roby/Roby/Task leads to (full backtrace: [backtrace.txt](https://github.com/docmeta/rubydoc.info/files/4846227/backtrace.txt))

Running yard 0.9.25 locally works.

~~~
undefined method `parameters' for #<yardoc class Roby::Task>
/usr/local/bundle/ruby/2.7.0/bundler/gems/yard-ca59056a5c70/lib/yard/code_objects/base.rb:378:in `method_missing'
/usr/local/bundle/ruby/2.7.0/bundler/gems/yard-ca59056a5c70/templates/default/tags/html/option.erb:4:in `_erb_cache_14'
/usr/local/bundle/ruby/2.7.0/bundler/gems/yard-ca59056a5c70/lib/yard/templates/template.rb:287:in `erb'
/usr/local/bundle/ruby/2.7.0/bundler/gems/yard-ca59056a5c70/lib/yard/templates/template.rb:369:in `render_section'
/usr/local/bundle/ruby/2.7.0/bundler/gems/yard-ca59056a5c70/lib/yard/templates/template.rb:259:in `block (2 levels) in run'
/usr/local/bundle/ruby/2.7.0/bundler/gems/yard-ca59056a5c70/lib/yard/templates/template.rb:256:in `each'
/usr/local/bundle/ruby/2.7.0/bundler/gems/yard-ca59056a5c70/lib/yard/templates/template.rb:256:in `block in run'
/usr/local/bundle/ruby/2.7.0/bundler/gems/yard-ca59056a5c70/lib/yard/templates/template.rb:398:in `add_options'
/usr/local/bundle/ruby/2.7.0/bundler/gems/yard-ca59056a5c70/lib/yard/templates/template.rb:255:in `run'
/usr/local/bundle/ruby/2.7.0/bundler/gems/yard-ca59056a5c70/lib/yard/templates/template.rb:277:in `block in yieldall'
/usr/local/bundle/ruby/2.7.0/bundler/gems/yard-ca59056a5c70/lib/yard/templates/template.rb:412:in `with_section'
/usr/local/bundle/ruby/2.7.0/bundler/gems/yard-ca59056a5c70/lib/yard/templates/template.rb:277:in `yieldall'
~~~

**Comment by lsegal** [comment]
This is probably due to Roby's use of plugins with YARD local builds: https://github.com/rock-core/tools-roby/blob/master/lib/roby/yard.rb

Custom plugins are supported during build phase but not for templating (unless whitelisted), so it's possible that the plugin is parsing code in a way that is not compatible with a default un-modified template.

**Comment by doudou** [comment]
Not sure I fully understand. I don't use a custom template (or at least I don't think I do).

How could I test this locally ?

**Comment by lsegal** [comment]
Closing out some old issues that have likely been resolved since the original report. If this is still a problem please reopen, thanks!

(Note: this is a bulk message, apologies in advance if this feels impersonal)
